INSERT INTO menu_items VALUES(0,'BBQ Chicken','hot sandwich',9.50);
INSERT INTO menu_items VALUES(1,'BBQ Tri-Tip','hot sandwich',9.50);
INSERT INTO menu_items VALUES(2,'California Chicken Breast Sandwich','hot sandwich',8.95);
INSERT INTO menu_items VALUES(3,'California Pastrami','hot sandwich',9.95);
INSERT INTO menu_items VALUES(4,'Chicken Caesar Sandwhich','hot sandwich',8.95);
INSERT INTO menu_items VALUES(5,'Chicken Italiano','hot sandwich',8.95);
INSERT INTO menu_items VALUES(6,'Classic Reuben','hot sandwich',9.95);
INSERT INTO menu_items VALUES(7,'Eggplant Artichoke Panini','hot sandwich',8.50);
INSERT INTO menu_items VALUES(8,'French Dip','hot sandwich',9.95);
INSERT INTO menu_items VALUES(9,'Grilled Cajun Turkey','hot sandwich',8.95);
INSERT INTO menu_items VALUES(10,'Hot Ham & Cheese','hot sandwich',8.95);
INSERT INTO menu_items VALUES(11,'Hot Roast Beef','hot sandwich',9.95);
INSERT INTO menu_items VALUES(12,'Monterey Chicken Club','hot sandwich',9.50);
INSERT INTO menu_items VALUES(13,'Philly Cheesesteak','hot sandwich',9.95);
INSERT INTO menu_items VALUES(14,'Southwestern Chicken Sandwhich','hot sandwich',8.95);
INSERT INTO menu_items VALUES(15,'Tomato-Basil Mozzarella Panini','hot sandwich',8.50);
INSERT INTO menu_items VALUES(16,'Tuna Melt','hot sandwich',8.95);
INSERT INTO menu_items VALUES(17,'Turkey Bacon Melt','hot sandwich',9.50);
INSERT INTO menu_items VALUES(18,'Turkey Dip','hot sandwich',8.95);
INSERT INTO menu_items VALUES(19,'Turkey Pesto Panini','hot sandwich',8.95);
INSERT INTO menu_items VALUES(20,'Albacore Tuna Sandwhich','cold sandwich',7.95);
INSERT INTO menu_items VALUES(21,'BLT','cold sandwich',7.95);
INSERT INTO menu_items VALUES(22,'Cajun Turkey','cold sandwich',8.95);
INSERT INTO menu_items VALUES(23,'Chicken & Bacon Club','cold sandwich',9.25);
INSERT INTO menu_items VALUES(24,'Club Deluxe','cold sandwich',9.25);
INSERT INTO menu_items VALUES(25,'Cracked Pepper Turkey','cold sandwich',8.95);
INSERT INTO menu_items VALUES(26,'Egg Salad Sandwhich','cold sandwich',7.95);
INSERT INTO menu_items VALUES(27,'Ham & Baby Swiss','cold sandwich',8.95);
INSERT INTO menu_items VALUES(28,'Heart Smart - Ham','cold sandwich',6.95);
INSERT INTO menu_items VALUES(29,'Heart Smart - Turkey','cold sandwich',6.95);
INSERT INTO menu_items VALUES(30,'Roast Beef','cold sandwich',9.25);
INSERT INTO menu_items VALUES(31,'Roast Turkey Breast','cold sandwich',8.95);
INSERT INTO menu_items VALUES(32,'Sequoia Chicken Wrap','cold sandwich',7.95);
INSERT INTO menu_items VALUES(33,'The Sicilian','cold sandwich',8.95);
INSERT INTO menu_items VALUES(34,'Waldorf Chicken Sandwich','cold sandwich',8.95);
INSERT INTO menu_items VALUES(35,'Chicago Pastrami','supreme sandwich',11.95);
INSERT INTO menu_items VALUES(36,'Double Hot Ham & Cheese','supreme sandwiches',10.95);
INSERT INTO menu_items VALUES(37,'Hot Beef Ortega Melt', 'supreme sandwich',11.95);
INSERT INTO menu_items VALUES(38,'Southwestern Tri-Tip','supreme sandwich', 11.95);
INSERT INTO menu_items VALUES(39,'The All American','supreme sandwich',10.95);
INSERT INTO menu_items VALUES(40,'The Big Dipper','supreme sandwich',11.95);
INSERT INTO menu_items VALUES(41,'The Italian Stallion','supreme sandwich',10.95);
INSERT INTO menu_items VALUES(42,'The New Yorker','supreme sandwich',11.95);
INSERT INTO menu_items VALUES(43,'Turkey Club','supreme sandwich',10.95);
INSERT INTO menu_items VALUES(44,'Cold Veggie & Cheese','vegetarian sandwich',6.95);
INSERT INTO menu_items VALUES(45,'Deluxe Grilled Cheese','vegetarian sandwich',6.95);
INSERT INTO menu_items VALUES(46,'Eggplant-Artichoke Panini','vegetarian sandwich',8.50);
INSERT INTO menu_items VALUES(47,'Hot Vegetarian','vegetarian sandwich',7.50);
INSERT INTO menu_items VALUES(48,'Tomato-Basil Mozzarella Panini','vegetarian sandwich',8.50);
INSERT INTO menu_items VALUES(49,'Banana Pudding','bakery',3.95);
INSERT INTO menu_items VALUES(50,'Butter Cake','bakery',2.95);
INSERT INTO menu_items VALUES(51,'Carrot Cake','bakery',3.25);
INSERT INTO menu_items VALUES(52,'Frosted Fudge Brownies','bakery',1.95);
INSERT INTO menu_items VALUES(53,'Garys Famous Chocolate Cake','bakery',2.95);
INSERT INTO menu_items VALUES(54,'German Chocolate Cake','bakery',3.95);
INSERT INTO menu_items VALUES(55,'Homemade Cookies','bakery',1.95);
INSERT INTO menu_items VALUES(56,'Homemade New York Cheesecake','bakery',3.75);
INSERT INTO menu_items VALUES(57,'New York Cheesecake w/strawberry sauce','bakery',3.95);
INSERT INTO menu_items VALUES(58,'Rice Krispy Treat','bakery',1.95);
INSERT INTO menu_items VALUES(59,'Straberries-n-Cream','bakery',4.95);
INSERT INTO menu_items VALUES(60,'Bottled Soda','beverage',2.25);
INSERT INTO menu_items VALUES(61,'Bottled Water','beverage',1.75);
INSERT INTO menu_items VALUES(62,'Iced Tea','beverage',2.25);
INSERT INTO menu_items VALUES(63,'Regular Fountain Drink','beverage',2.25);
INSERT INTO menu_items VALUES(64,'Sparkling Water','beverage',1.95);
commit;